// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApj50C4WTmhCHMALVMJGajehaJXEaq8Jc',
    appId: '1:1036618900974:web:57b952f1d146cf950c9aff',
    messagingSenderId: '1036618900974',
    projectId: 'message-board-app-af730',
    authDomain: 'message-board-app-af730.firebaseapp.com',
    storageBucket: 'message-board-app-af730.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANpMOBj6OhC6yahox8Uc-JA--on7GAIbw',
    appId: '1:1036618900974:android:01baaaec13392dc80c9aff',
    messagingSenderId: '1036618900974',
    projectId: 'message-board-app-af730',
    storageBucket: 'message-board-app-af730.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxWl2ZxS7GXngw7GkCuL0BmINe6CgfQDs',
    appId: '1:1036618900974:ios:b39074478728cc100c9aff',
    messagingSenderId: '1036618900974',
    projectId: 'message-board-app-af730',
    storageBucket: 'message-board-app-af730.firebasestorage.app',
    iosBundleId: 'com.example.messageBoardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxWl2ZxS7GXngw7GkCuL0BmINe6CgfQDs',
    appId: '1:1036618900974:ios:b39074478728cc100c9aff',
    messagingSenderId: '1036618900974',
    projectId: 'message-board-app-af730',
    storageBucket: 'message-board-app-af730.firebasestorage.app',
    iosBundleId: 'com.example.messageBoardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApj50C4WTmhCHMALVMJGajehaJXEaq8Jc',
    appId: '1:1036618900974:web:ddca5077e84f7f3c0c9aff',
    messagingSenderId: '1036618900974',
    projectId: 'message-board-app-af730',
    authDomain: 'message-board-app-af730.firebaseapp.com',
    storageBucket: 'message-board-app-af730.firebasestorage.app',
  );
}
