// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS6kJZaOEUV1b9BQOpzriLtpJOUTbJhkQ',
    appId: '1:875747700832:web:a2f0deca4750c93ff8d305',
    messagingSenderId: '875747700832',
    projectId: 'message-board-app-v2',
    authDomain: 'message-board-app-v2.firebaseapp.com',
    storageBucket: 'message-board-app-v2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdgZJc-pCpbjIuxM3-qe0H2x3P8xdGKIo',
    appId: '1:875747700832:android:6e9c9776e8758bcdf8d305',
    messagingSenderId: '875747700832',
    projectId: 'message-board-app-v2',
    storageBucket: 'message-board-app-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs3_EdSZkMdZFxiQHs-Q2xiONoa_4sleQ',
    appId: '1:875747700832:ios:09c9cffcd5033d64f8d305',
    messagingSenderId: '875747700832',
    projectId: 'message-board-app-v2',
    storageBucket: 'message-board-app-v2.firebasestorage.app',
    iosBundleId: 'com.example.messageBoardAppV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs3_EdSZkMdZFxiQHs-Q2xiONoa_4sleQ',
    appId: '1:875747700832:ios:09c9cffcd5033d64f8d305',
    messagingSenderId: '875747700832',
    projectId: 'message-board-app-v2',
    storageBucket: 'message-board-app-v2.firebasestorage.app',
    iosBundleId: 'com.example.messageBoardAppV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAS6kJZaOEUV1b9BQOpzriLtpJOUTbJhkQ',
    appId: '1:875747700832:web:3fa947ff226a8f0af8d305',
    messagingSenderId: '875747700832',
    projectId: 'message-board-app-v2',
    authDomain: 'message-board-app-v2.firebaseapp.com',
    storageBucket: 'message-board-app-v2.firebasestorage.app',
  );

}